name: Generate Diagram PNGs from .drawio files

on:
  push:
    paths:
      - '**/*.drawio'

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install draw.io CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y drawio
        
      - name: Convert .drawio files to PNG
        run: |
          for file in $(find . -name '*.drawio'); do
            drawio --export "$file" --output "${file%.drawio}.png"
          done

      # Commit changes
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Auto-update PNGs from .drawio"
          git push

      # Upload the PNGs as an artifact (if necessary)
      - name: Upload PNG files
        uses: actions/upload-artifact@v3
        with:
          name: generated-diagrams
          path: '**/*.png'
